{% set name = "sphinxcontrib-googleanalytics" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a2ac6df9d16b9c124febf6b44e714c1fd9725e692b73ee84ec6b52b377ff5561

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - sphinx >=0.6

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/googleanalytics
  summary: Sphinx extension googleanalytics
  license: BSD-4.3TAHOE
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zaneselvans
